package cc.minis.image2studio;

import android.app.*;import android.os.*;import android.provider.MediaStore;import android.content.*;import android.content.pm.PackageManager;import android.Manifest;import android.net.*;import android.graphics.*;import android.util.Base64;import android.webkit.*;import android.widget.*;import android.view.*;import org.json.*;import java.io.*;import java.net.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity{
 static final int REQ_PICK=77,REQ_CAMERA=78,REQ_NOTIF=79;static final String DEF_BASE="https://factory.pub",DEF_MODEL="gpt-image-2";WebView web;SharedPreferences sp;ArrayList<Uri> selectedUris=new ArrayList<Uri>();ArrayList<String> currentPaths=new ArrayList<String>();Uri cameraUri;
 public void onCreate(Bundle b){super.onCreate(b);System.setProperty("http.keepAlive","false");sp=getSharedPreferences("image2studio",MODE_PRIVATE);web=new WebView(this);setContentView(web);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(true);s.setAllowContentAccess(true);web.setWebViewClient(new WebViewClient());web.addJavascriptInterface(new Bridge(),"Android");web.loadUrl("file:///android_asset/index.html");}
 public void onRequestPermissionsResult(int requestCode,String[] permissions,int[] grantResults){super.onRequestPermissionsResult(requestCode,permissions,grantResults);if(requestCode==REQ_NOTIF)sendPermissionStatus();}
 boolean hasNotificationPermission(){return Build.VERSION.SDK_INT<33||checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED;}
 void requestNotificationPermission(){if(Build.VERSION.SDK_INT>=33&&!hasNotificationPermission())requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},REQ_NOTIF);}
 void ensureNotifyPermission(){if(!hasNotificationPermission())requestNotificationPermission();}
 void sendPermissionStatus(){try{JSONObject j=new JSONObject();j.put("needPermission",Build.VERSION.SDK_INT>=33);j.put("notificationGranted",hasNotificationPermission());j.put("canForeground",true);cb("onPermissionStatus",j.toString());}catch(Exception ignored){}}
 void openAppNotificationSettings(){try{Intent it=new Intent(android.provider.Settings.ACTION_APP_NOTIFICATION_SETTINGS);it.putExtra(android.provider.Settings.EXTRA_APP_PACKAGE,getPackageName());startActivity(it);}catch(Exception e){try{Intent it=new Intent(android.provider.Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName()));startActivity(it);}catch(Exception ignored){}}}
 void cb(final String fn,final String json){runOnUiThread(new Runnable(){public void run(){web.evaluateJavascript("window."+fn+" && window."+fn+"("+json+")",null);}});}String esc(String s){return JSONObject.quote(s==null?"":s);}String now(){return new SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.CHINA).format(new Date());}
 public class Bridge{
  @JavascriptInterface public String getSettings(){try{JSONObject j=new JSONObject();j.put("baseUrl",sp.getString("base",DEF_BASE));j.put("model",sp.getString("model",DEF_MODEL));j.put("apiKey",sp.getString("key",""));j.put("remember",sp.getBoolean("remember",false));return j.toString();}catch(Exception e){return"{}";}}
  @JavascriptInterface public void saveSettings(String json){try{JSONObject j=new JSONObject(json);SharedPreferences.Editor e=sp.edit();e.putString("base",clean(j.optString("baseUrl",DEF_BASE)));e.putString("model",j.optString("model",DEF_MODEL));e.putBoolean("remember",j.optBoolean("remember",false));if(j.optBoolean("remember",false))e.putString("key",j.optString("apiKey",""));else e.remove("key");e.apply();}catch(Exception ignored){}}
  @JavascriptInterface public void requestModels(final String rid,final String base,final String key){new Thread(new Runnable(){public void run(){try{HttpURLConnection c=conn(clean(base)+"/v1/models","GET",key,null);String body=readAll(c);if(c.getResponseCode()/100!=2)throw new Exception(err(body));cb("nativeResolve",new JSONObject().put("id",rid).put("ok",true).put("body",new JSONObject(body)).toString());}catch(Exception e){logError("request",e);cb("nativeResolve",errObj(rid,e));}}}).start();}
  @JavascriptInterface public void autoSelectImage2Model(){new Thread(new Runnable(){public void run(){try{String key=sp.getString("key","");if(key.trim().length()==0){cb("onAutoModel",new JSONObject().put("ok",false).put("error","未保存 API Key").toString());return;}String base=sp.getString("base",DEF_BASE);HttpURLConnection c=conn(clean(base)+"/v1/models","GET",key,null);String body=readAll(c);if(c.getResponseCode()/100!=2)throw new Exception(err(body));JSONObject j=new JSONObject(body);JSONArray data=j.optJSONArray("data");String chosen=chooseImage2Model(data);if(chosen.length()==0)chosen=DEF_MODEL;sp.edit().putString("model",chosen).apply();cb("onAutoModel",new JSONObject().put("ok",true).put("model",chosen).toString());}catch(Exception e){logError("auto_select_model",e);cb("onAutoModel","{\"ok\":false,\"error\":"+esc(e.getMessage())+"}");}}}).start();}
  @JavascriptInterface public void openUrl(String url){try{Intent it=new Intent(Intent.ACTION_VIEW,Uri.parse(url));startActivity(it);}catch(Exception e){Toast.makeText(MainActivity.this,"打开链接失败："+e.getMessage(),Toast.LENGTH_LONG).show();}}
  @JavascriptInterface public void requestNotificationPermission(){runOnUiThread(new Runnable(){public void run(){MainActivity.this.requestNotificationPermission();sendPermissionStatus();}});}
  @JavascriptInterface public String getPermissionStatus(){try{JSONObject j=new JSONObject();j.put("needPermission",Build.VERSION.SDK_INT>=33);j.put("notificationGranted",hasNotificationPermission());j.put("canForeground",true);j.put("sdk",Build.VERSION.SDK_INT);return j.toString();}catch(Exception e){return"{}";}}
  @JavascriptInterface public void openNotificationSettings(){runOnUiThread(new Runnable(){public void run(){openAppNotificationSettings();}});}
  @JavascriptInterface public void generateText(final String rid,final String base,final String key,final String model,final String prompt,final String neg,final int n,final String ratio,final String quality){ensureNotifyPermission();GenerationService.start(MainActivity.this);new Thread(new Runnable(){public void run(){try{JSONObject req=new JSONObject();req.put("model",model);req.put("prompt",promptPlus(prompt,ratio,quality));req.put("n",n);String size=sizeFor(ratio,quality);if(size.length()>0)req.put("size",size);if(neg!=null&&neg.trim().length()>0)req.put("negative_prompt",neg);HttpURLConnection c=conn(clean(base)+"/v1/images/generations","POST",key,"application/json");c.getOutputStream().write(req.toString().getBytes("UTF-8"));String body=readAll(c);if(c.getResponseCode()/100!=2)throw new Exception(err(body));ArrayList<Item> items=parseAndPersist(body);addHistory("文生图",prompt,items);GenerationService.done(MainActivity.this);cb("nativeResolve",new JSONObject().put("id",rid).put("ok",true).put("items",itemsJson(items)).toString());}catch(Exception e){GenerationService.fail(MainActivity.this);logError("request",e);cb("nativeResolve",errObj(rid,e));}}}).start();}
  @JavascriptInterface public void pickImages(){Intent it;if(Build.VERSION.SDK_INT>=33){it=new Intent(MediaStore.ACTION_PICK_IMAGES);it.putExtra(MediaStore.EXTRA_PICK_IMAGES_MAX,4);}else{it=new Intent(Intent.ACTION_PICK,MediaStore.Images.Media.EXTERNAL_CONTENT_URI);it.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);}startActivityForResult(it,REQ_PICK);}
  @JavascriptInterface public void captureImage(){try{imgDir().mkdirs();File f=new File(imgDir(),"camera_"+System.currentTimeMillis()+".jpg");cameraUri=Uri.parse("content://cc.minis.image2studio.share/"+f.getName());Intent it=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);it.putExtra(MediaStore.EXTRA_OUTPUT,cameraUri);it.addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivityForResult(it,REQ_CAMERA);}catch(Exception e){Toast.makeText(MainActivity.this,"打开相机失败："+e.getMessage(),Toast.LENGTH_LONG).show();}}
  @JavascriptInterface public void removePickedImage(int index){if(index>=0&&index<selectedUris.size())selectedUris.remove(index);cb("onImagesPicked","{"+"\"count\":"+selectedUris.size()+",\"uris\":"+pickedJson()+"}");}
  @JavascriptInterface public void generateEdit(final String rid,final String base,final String key,final String model,final String prompt,final int n,final String ratio,final String quality){ensureNotifyPermission();GenerationService.start(MainActivity.this);new Thread(new Runnable(){public void run(){try{if(selectedUris.size()==0)throw new Exception("请先选择参考图");String boundary="----Image2Studio"+System.currentTimeMillis();HttpURLConnection c=conn(clean(base)+"/v1/images/edits","POST",key,"multipart/form-data; boundary="+boundary);OutputStream out=c.getOutputStream();part(out,boundary,"model",model);part(out,boundary,"prompt",promptPlus(prompt,ratio,quality));part(out,boundary,"n",String.valueOf(n));String size=sizeFor(ratio,quality);if(size.length()>0)part(out,boundary,"size",size);for(int i=0;i<selectedUris.size();i++)filePart(out,boundary,"image","ref"+i+".png",selectedUris.get(i));out.write(("--"+boundary+"--\r\n").getBytes("UTF-8"));String body=readAll(c);if(c.getResponseCode()/100!=2)throw new Exception(err(body));ArrayList<Item> items=parseAndPersist(body);addHistory("图生图",prompt,items);GenerationService.done(MainActivity.this);cb("nativeResolve",new JSONObject().put("id",rid).put("ok",true).put("items",itemsJson(items)).toString());}catch(Exception e){GenerationService.fail(MainActivity.this);logError("request",e);cb("nativeResolve",errObj(rid,e));}}}).start();}
  @JavascriptInterface public String loadHistory(){return sp.getString("history","[]");}
  @JavascriptInterface public String isErrorLogEnabled(){return sp.getBoolean("errorLog",false)?"true":"false";}
  @JavascriptInterface public void setErrorLogEnabled(boolean on){sp.edit().putBoolean("errorLog",on).apply();}
  @JavascriptInterface public String listErrorLogs(){try{JSONArray a=new JSONArray();File[] fs=logDir().listFiles();if(fs!=null){Arrays.sort(fs,new Comparator<File>(){public int compare(File x,File y){return Long.compare(y.lastModified(),x.lastModified());}});for(File f:fs)if(f.isFile()&&f.getName().endsWith(".log"))a.put(new JSONObject().put("name",f.getName()).put("size",fmtSize(f.length())));}return a.toString();}catch(Exception e){return"[]";}}
  @JavascriptInterface public void shareErrorLog(String name){runOnUiThread(new Runnable(){public void run(){try{shareLog(name);}catch(Exception e){Toast.makeText(MainActivity.this,"分享日志失败："+e.getMessage(),Toast.LENGTH_LONG).show();}}});}
  @JavascriptInterface public void clearHistory(){File[] fs=imgDir().listFiles();if(fs!=null)for(File f:fs)f.delete();sp.edit().remove("history").apply();}
  @JavascriptInterface public void deleteHistoryItem(int index){try{JSONArray old=new JSONArray(sp.getString("history","[]"));JSONArray next=new JSONArray();for(int i=0;i<old.length();i++){JSONObject item=old.getJSONObject(i);if(i==index){JSONArray ps=item.optJSONArray("paths");if(ps!=null)for(int j=0;j<ps.length();j++){String p=ps.optString(j,"");if(p.length()>0)new File(p).delete();}}else next.put(item);}sp.edit().putString("history",next.toString()).apply();}catch(Exception ignored){}}
  @JavascriptInterface public void saveCurrentToGallery(final String rid){new Thread(new Runnable(){public void run(){try{int ok=savePaths(currentPaths);cb("nativeResolve",new JSONObject().put("id",rid).put("ok",true).put("saved",ok).toString());}catch(Exception e){logError("request",e);cb("nativeResolve",errObj(rid,e));}}}).start();}
  @JavascriptInterface public void saveHistoryItemToGallery(final String rid,final String jsonPaths){new Thread(new Runnable(){public void run(){try{JSONArray a=new JSONArray(jsonPaths);ArrayList<String> ps=new ArrayList<String>();for(int i=0;i<a.length();i++)ps.add(a.optString(i));int ok=savePaths(ps);cb("nativeResolve",new JSONObject().put("id",rid).put("ok",true).put("saved",ok).toString());}catch(Exception e){logError("request",e);cb("nativeResolve",errObj(rid,e));}}}).start();}
  @JavascriptInterface public void shareCurrent(){runOnUiThread(new Runnable(){public void run(){try{if(currentPaths.size()==0){Toast.makeText(MainActivity.this,"没有可分享图片",Toast.LENGTH_SHORT).show();return;}sharePath(currentPaths.get(0));}catch(Exception e){Toast.makeText(MainActivity.this,"分享失败："+e.getMessage(),Toast.LENGTH_LONG).show();}}});}
  @JavascriptInterface public void editCurrent(){runOnUiThread(new Runnable(){public void run(){try{if(currentPaths.size()==0){Toast.makeText(MainActivity.this,"没有可编辑图片",Toast.LENGTH_SHORT).show();return;}setEditSource(currentPaths.get(0));}catch(Exception e){Toast.makeText(MainActivity.this,"编辑失败："+e.getMessage(),Toast.LENGTH_LONG).show();}}});}
  @JavascriptInterface public void shareHistoryItem(final String jsonPaths){runOnUiThread(new Runnable(){public void run(){try{JSONArray a=new JSONArray(jsonPaths);if(a.length()==0){Toast.makeText(MainActivity.this,"没有可分享图片",Toast.LENGTH_SHORT).show();return;}String p=a.optString(0,"");if(p.length()==0){Toast.makeText(MainActivity.this,"没有可分享图片",Toast.LENGTH_SHORT).show();return;}sharePath(p);}catch(Exception e){Toast.makeText(MainActivity.this,"分享失败："+e.getMessage(),Toast.LENGTH_LONG).show();}}});}
  @JavascriptInterface public void editHistoryItem(final String jsonPaths){runOnUiThread(new Runnable(){public void run(){try{JSONArray a=new JSONArray(jsonPaths);if(a.length()==0){Toast.makeText(MainActivity.this,"没有可编辑图片",Toast.LENGTH_SHORT).show();return;}String p=a.optString(0,"");if(p.length()==0){Toast.makeText(MainActivity.this,"没有可编辑图片",Toast.LENGTH_SHORT).show();return;}setEditSource(p);}catch(Exception e){Toast.makeText(MainActivity.this,"编辑失败："+e.getMessage(),Toast.LENGTH_LONG).show();}}});}
 }
 protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r==REQ_PICK&&c==RESULT_OK&&data!=null){selectedUris.clear();if(data.getClipData()!=null){for(int i=0;i<data.getClipData().getItemCount()&&i<4;i++)selectedUris.add(data.getClipData().getItemAt(i).getUri());}else if(data.getData()!=null)selectedUris.add(data.getData());cb("onImagesPicked","{"+"\"count\":"+selectedUris.size()+",\"uris\":"+pickedJson()+"}");}else if(r==REQ_CAMERA&&c==RESULT_OK&&cameraUri!=null){selectedUris.clear();selectedUris.add(cameraUri);cb("onImagesPicked","{"+"\"count\":"+selectedUris.size()+",\"uris\":"+pickedJson()+"}");}}
 String pickedJson(){JSONArray a=new JSONArray();try{for(Uri u:selectedUris)a.put(u.toString());}catch(Exception e){}return a.toString();}
 String clean(String s){if(s==null||s.trim().length()==0)s=DEF_BASE;s=s.trim();while(s.endsWith("/"))s=s.substring(0,s.length()-1);return s;}HttpURLConnection conn(String u,String m,String key,String type)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setRequestMethod(m);c.setConnectTimeout(20000);c.setReadTimeout(180000);c.setRequestProperty("Authorization","Bearer "+key);c.setRequestProperty("Accept","application/json");c.setRequestProperty("Connection","close");c.setRequestProperty("Cache-Control","no-cache");c.setUseCaches(false);if(type!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type",type);}return c;}String readAll(HttpURLConnection c)throws Exception{InputStream is;try{is=c.getInputStream();}catch(Exception e){is=c.getErrorStream();}if(is==null)return"";BufferedReader br=new BufferedReader(new InputStreamReader(is,"UTF-8"));StringBuilder sb=new StringBuilder();String line;while((line=br.readLine())!=null)sb.append(line).append('\n');return sb.toString();}String err(String b){try{JSONObject j=new JSONObject(b);JSONObject e=j.optJSONObject("error");if(e!=null&&e.optString("message").length()>0)return e.optString("message");}catch(Exception ignored){}return b.length()>500?b.substring(0,500):b;}String errObj(String id,Exception e){try{return new JSONObject().put("id",id).put("ok",false).put("error",e.getMessage()).toString();}catch(Exception x){return"{\"ok\":false}";}}
 String promptPlus(String p,String r,String q){String e="";if(!"Auto".equals(r))e+=", "+r+" aspect ratio";if("4K".equals(q))e+=", true 4K, ultra detailed";return p+e;}String sizeFor(String r,String q){if(!"4K".equals(q))return"";if("16:9".equals(r))return"3840x2160";if("9:16".equals(r))return"2160x3840";if("1:1".equals(r))return"2880x2880";if("4:3".equals(r))return"3200x2400";if("3:4".equals(r))return"2400x3200";return"2880x2880";}
 String chooseImage2Model(JSONArray data){try{if(data==null||data.length()==0)return"";String first="";for(int i=0;i<data.length();i++){String id=data.getJSONObject(i).optString("id","");if(first.length()==0)first=id;if("gpt-image-2".equalsIgnoreCase(id))return id;}for(int i=0;i<data.length();i++){String id=data.getJSONObject(i).optString("id","");String low=id.toLowerCase(Locale.US);if(low.contains("image2")||low.contains("image-2")||low.contains("gpt-image"))return id;}return first;}catch(Exception e){return"";}}
 void part(OutputStream o,String b,String n,String v)throws Exception{o.write(("--"+b+"\r\nContent-Disposition: form-data; name=\""+n+"\"\r\n\r\n"+v+"\r\n").getBytes("UTF-8"));}void filePart(OutputStream o,String b,String n,String f,Uri u)throws Exception{o.write(("--"+b+"\r\nContent-Disposition: form-data; name=\""+n+"\"; filename=\""+f+"\"\r\nContent-Type: image/png\r\n\r\n").getBytes("UTF-8"));InputStream in=getContentResolver().openInputStream(u);byte[] buf=new byte[8192];int len;while((len=in.read(buf))>0)o.write(buf,0,len);in.close();o.write("\r\n".getBytes("UTF-8"));}
 static class Item{String path,url;Item(String p,String u){path=p;url=u;}}File imgDir(){return new File(getFilesDir(),"images");}ArrayList<Item> parseAndPersist(String body)throws Exception{ArrayList<Item> out=new ArrayList<Item>();JSONObject j=new JSONObject(body);JSONArray a=j.optJSONArray("data");if(a==null)return out;imgDir().mkdirs();currentPaths.clear();for(int i=0;i<a.length();i++){JSONObject it=a.getJSONObject(i);String url=it.optString("url","");String b64=it.optString("b64_json","");if(b64.length()==0)b64=it.optString("b64","");Bitmap bm=null;if(url.length()>0)bm=BitmapFactory.decodeStream(new URL(url).openStream());else if(b64.length()>0){String raw=b64.startsWith("data:")?b64.substring(b64.indexOf(',')+1):b64;byte[] bytes=Base64.decode(raw,Base64.DEFAULT);bm=BitmapFactory.decodeByteArray(bytes,0,bytes.length);}if(bm!=null){File f=new File(imgDir(),"image2_"+System.currentTimeMillis()+"_"+i+".png");FileOutputStream fos=new FileOutputStream(f);bm.compress(Bitmap.CompressFormat.PNG,100,fos);fos.close();out.add(new Item(f.getAbsolutePath(),url));currentPaths.add(f.getAbsolutePath());}}return out;}JSONArray itemsJson(ArrayList<Item> items)throws Exception{JSONArray a=new JSONArray();for(Item it:items)a.put(new JSONObject().put("path",it.path).put("url",it.url).put("fileUrl","file://"+it.path));return a;}void addHistory(String mode,String prompt,ArrayList<Item> items)throws Exception{JSONArray old=new JSONArray(sp.getString("history","[]"));JSONObject o=new JSONObject();o.put("time",now());o.put("mode",mode);o.put("prompt",prompt);JSONArray ps=new JSONArray();for(Item it:items)ps.put(it.path);o.put("paths",ps);JSONArray n=new JSONArray();n.put(o);for(int i=0;i<old.length()&&i<19;i++)n.put(old.getJSONObject(i));sp.edit().putString("history",n.toString()).apply();}
 int savePaths(ArrayList<String> paths)throws Exception{int ok=0;for(String p:paths){Bitmap bm=BitmapFactory.decodeFile(p);if(bm==null)continue;ContentValues cv=new ContentValues();cv.put(MediaStore.Images.Media.DISPLAY_NAME,"Image2Studio_"+System.currentTimeMillis()+".png");cv.put(MediaStore.Images.Media.MIME_TYPE,"image/png");if(Build.VERSION.SDK_INT>=29)cv.put(MediaStore.Images.Media.RELATIVE_PATH,"Pictures/Image2Studio");Uri uri=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,cv);if(uri==null)continue;OutputStream os=getContentResolver().openOutputStream(uri);bm.compress(Bitmap.CompressFormat.PNG,100,os);os.close();ok++;}return ok;}
 void sharePath(String path){File f=new File(path);Uri uri=Uri.parse("content://cc.minis.image2studio.share/"+f.getName());Intent it=new Intent(Intent.ACTION_SEND);it.setType("image/png");it.putExtra(Intent.EXTRA_STREAM,uri);it.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(it,"分享图片"));}
 void setEditSource(String path)throws Exception{File f=new File(path);if(!f.exists())throw new FileNotFoundException(path);selectedUris.clear();selectedUris.add(Uri.fromFile(f));cb("onImagesPicked","{"+"\"count\":"+selectedUris.size()+",\"uris\":"+pickedJson()+"}");runOnUiThread(new Runnable(){public void run(){web.evaluateJavascript("document.querySelector('[data-page=edit]').click();toast('已载入图片，可继续编辑')",null);}});}
 File logDir(){File d=new File(getFilesDir(),"error_logs");d.mkdirs();return d;}String logDate(){return new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date());}String logTime(){return new SimpleDateFormat("yyyy-MM-dd HH:mm:ss",Locale.US).format(new Date());}
 void logError(String area,Exception e){try{if(!sp.getBoolean("errorLog",false))return;String msg=e==null?"unknown":String.valueOf(e.getMessage());msg=sanitizeLog(msg);File f=new File(logDir(),"image2studio-"+logDate()+".log");FileWriter w=new FileWriter(f,true);w.write(logTime()+" [ERROR] "+sanitizeLog(area)+" - "+msg+"\n");w.close();}catch(Exception ignored){}}
 String sanitizeLog(String s){if(s==null)return"";s=s.replaceAll("(?i)Bearer\\s+[A-Za-z0-9._\\-]+","Bearer ***");s=s.replaceAll("sk-[A-Za-z0-9._\\-]+","sk-***");s=s.replaceAll("(?i)(api[_ -]?key|authorization|token|password)[=: ]+[^\\s,;]+","$1=***");if(s.length()>600)s=s.substring(0,600);return s;}
 String fmtSize(long n){if(n>=1048576)return String.format(Locale.US,"%.2f MB",n/1048576.0);if(n>=1024)return String.format(Locale.US,"%.1f KB",n/1024.0);return n+" B";}
 void shareLog(String name){if(name==null||name.contains("/")||name.contains("..")||!name.endsWith(".log"))throw new IllegalArgumentException("bad log");File f=new File(logDir(),name);if(!f.exists())throw new IllegalArgumentException("日志不存在");Uri uri=Uri.parse("content://cc.minis.image2studio.share/logs/"+f.getName());Intent it=new Intent(Intent.ACTION_SEND);it.setType("text/plain");it.putExtra(Intent.EXTRA_STREAM,uri);it.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(it,"分享日志"));}
}
